# Generated by Django 4.2.13 on 2024-07-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='category',
            field=models.CharField(choices=[('Groceries', 'Groceries'), ('Food', 'Food'), ('Entertainment', 'Entertainment'), ('Gas', 'Gas'), ('Housing', 'Housing'), ('Transportation', 'Transportation'), ('Health', 'Health'), ('Debt', 'Debt'), ('Education', 'Education'), ('Savings', 'Savings'), ('Investments', 'Investments')], default='food', max_length=20),
        ),
    ]
